### ISSUE TITLE
OSX Support

### ISSUE THREAD

**Issue by xhochy** [conda-forge/pyarrow-feedstock#8]
Currently we only have Linux builds. Is there a problem with the OSX ones?

**Comment by wesm** [comment]
it's blocked on https://github.com/conda-forge/conda-forge-enhancement-proposals/pull/6

**Comment by wesm** [comment]
I'm going to rerender the feedstock since they just made xcode6.4 the CF image

**Comment by wesm** [comment]
Ah looks like we need to wait for the conda-smithy release (last one was 28 days ago)

**Comment by jakirkham** [comment]
Yeah, sorry for the long turnaround on a release. Knew it was going to be a breaking one due to changes w.r.t. how channels are handled. Wanted to try to gather up all similar changes like dropping Python 3.4, NumPy 1.10, and bumping the Travis image for instance. Expect `conda-smithy` releases going forward to be a bit more regular.
